name: Build notes
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile files
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: Upload notes
        uses: actions/upload-artifact@v4
        with:
          name: notes.pdf
          path: main.pdf
